api:
  prefix: 'api'

http:
  port: 3000

db:
  postgres:
    schema: 'service_todo'
    migrationsRun: false
    write:
      host: '127.0.0.1'
      port: 5432
      user: 'postgres'
      password: 'password'
      database: 'development'
    read:
      host: '127.0.0.1'
      port: 5432
      user: 'postgres'
      password: 'password'
      database: 'development'
