api:
  prefix: 'api'

http:
  host: '127.0.0.1'
  port: 3000
  timeout: 5000
  max-redirects: 5

jwt:
  secret: 'secretKey'
  expire: '1h'

db:
  postgres:
    schema: 'nest_service_todo'
    write:
      host: '127.0.0.1'
      port: 5432
      user: 'dev'
      password: 'password'
      database: 'development'
    read:
      host: '127.0.0.1'
      port: 5432
      user: 'dev'
      password: 'password'
      database: 'development'

redis:
  db: 1
  host: '127.0.0.1'
  password: null
  port: 6379
  prefix: 'nest.api.todo::'
  ttl: 300
