api:
  prefix: 'api'

http:
  host: 'localhost'
  port: 3000

db:
  postgres:
    schema: 'nest_service_todo'
    write:
      host: '127.0.0.1'
      port: 5432
      user: 'dev'
      password: 'password'
      database: 'development'
    read:
      host: '127.0.0.1'
      port: 5432
      user: 'dev'
      password: 'password'
      database: 'development'
